version: '2'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
     - "127.0.0.1:3000:3000"
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    networks:
     - appnet
  influxdb:
    image: influxdb:latest
    ports:
      - "127.0.0.1:8083:8083"
      - "127.0.0.1:8086:8086"
      - "127.0.0.1:8090:8090"
      - "127.0.0.1:25826:25826"
      - "127.0.0.1:25826:25826/udp"
    volumes:  
      - ./data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./data/influxdb/types.db:/opt/collectd/types.db:ro
    networks:
     - appnet
  telegraf:
    image: telegraf:alpine
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    hostname: myhostname
    volumes:
      - ./data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/utmp:/var/run/utmp:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    links:
      - influxdb:container
    expose:
      - "8125/udp"
    ports:
      - "127.0.0.1:8125:8125/udp"
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
